apiVersion: v1
entries:
  nucleus:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-20T21:46:02.060158+01:00"
    description: A Helm chart for Kubernetes
    digest: f54e2ce644590dc3776f80ff4131cf5c1b7e2fa0ab2629ca98b5097d1770ec23
    name: nucleus
    type: application
    urls:
    - https://flawlessbyte.github.io/nucleus/charts/nucleus-1.0.0.tgz
    version: 1.0.0
generated: "2025-07-20T21:46:02.057763+01:00"
