{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ coalesce .Values.externalSecrets.name (include "nucleus.fullname" .) }}
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
  {{- if or .Values.externalSecrets.annotations (include "nucleus.annotations" .) }}
  annotations:
    {{- include "nucleus.annotations" . | nindent 4 }}
    {{- with .Values.externalSecrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval | default 0 }}"
  {{- with .Values.externalSecrets.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}